jenkins-infra/aws

.gitignore
Jenkinsfile_k8s
Makefile
backend.tf

This PR aims at removing the terraform S3 backend setup out of the repository, to move it as encrypted credentials depending on the target environment (ci for testing or production).
Requires https://github.com/jenkins-infra/charts/pull/920 to be merged and applied (any builds before are done with a temp. credential on infra.ci)

Move terraform backend configuration out of the repository

---

Jenkinsfile_k8s
Makefile
README.adoc
README.md

This PR enables linting of the terratest golang code using golangci-lint (as https://github.com/jenkins-infra/docker-terraform/pull/10 added this tool in the image)

Enable Terratest Linting

---

Jenkinsfile_k8s
README.adoc

Documentation (`README`) has been updated to describe the 4 foreseen use cases:
* PR: tests + terraform plan to show changes
* build on main, triggered by a code push: no tests, terraform plan, and terraform apply => either a PR merge or an admin's direct push to `main`
* Daily build on main (triggered by cron timer): run tests + a terraform plan with detailled exit code. If there are resource changes in the plan (e.g. a configuration drift between state, repo and production), then the plan fails
* Manual build on main (triggered by a human): no tests, terraform plan, and then wait for user manual input (1 hour max: the pipeline has a timeout). If a humans clicks "ship it", then terraform apply

Update Pipeline behavior to cover the 4 possible workflows

---

.gitignore
Jenkinsfile_k8s
ci-pod-template.yml
eks-cluster.tf
providers.tf
versions.tf

This PR introduces the following changes:
- Define a Kubernetes Provider in terraform to allow configuration of the configmap `aws-auth` in the EKS cluster, as per https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest#usage-example
- Bump image `jenkinsciinfra/terraform` to `1.3.0` to have the `aws` and `aws-iam-authenticator` CLIs available (+ move the pod template to a YAMLfile)
- Add 2 IAM users to the `aws-auth` configmap: `production-terraform` to allow CI to grant the admin clusterrole in the EKS cluster + the `infra-admin` that can be impersonnated by any member of the AWS account organizaton

Configure Kubernetes Auth from IAM

---

eks-cluster.tf

to get a fixed version over time

Fix: switch EKS worker's AMI to a datasource

---

ec2-agents.tf

INFRA-2904: add an EC2 keypair to allow infra.ci using ec2 agents

---

.terraform.lock.hcl
eks-cluster.tf
versions.tf
vpc.tf

This PR updates the repository to support Terraform 1.0.
It includes the following changes:
- Bump providers (to get rid of deprecated syntax from terraform <0.12):
* `hashicorp/aws` to [3.53.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.53.0)
* `hashicorp/kubernetes` to [2.4.1](https://github.com/hashicorp/terraform-provider-kubernetes/releases/tag/v2.4.1)
- Bump modules (to get rid of deprecated syntax from terraform <0.12):
* `terraform-aws-modules/eks/aws` to [17.1](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v17.1.0)
* `terraform-aws-modules/vpc/aws` to [3.3.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/CHANGELOG.md#v330---2021-08-10)
- Bump terraform project maximum version constraint to <1.1
- Add a …

feat: bump terraform to 1.0.4 + all required dependencies

---

eks-cluster.tf

This PR increases the ASG size to 50 VM max, to ensure there are enough resources available on ci.jenkins.io, as part of INFRA-2918.

feat: increase upper limit of the main-linux ASG to 50 [INFRA-2918]

---

eks-addons.tf

This PR follows up the Kubernetes 1.20 upgrade of EKS (in #44) .
It ensures that the EKS addons are now managed by Terraform, to ensure that it would be upgraded for the next cluster update (to 1.21).
To avoid errors due to IAM roles, we've initialized the addons for hte freshly upgraded 1.20 EKS cluster in AWS console WebUI, and the 3 resources had been imported in terraform in this PR with the following commands
```shell
terraform import aws_eks_addon.kube-proxy 'jenkins-infra-eks-ENRZrfwf:kube-proxy'
terraform import aws_eks_addon.coredns 'jenkins-infra-eks-ENRZrfwf:coredns'
terraform import aws_eks_addon.vpc-cni 'jenkins-infra-eks-ENRZrfwf:vpc-cni'
```

feat(eks) manage addons through terraform

---

eks-public-cluster.tf

Error message with a1.xlarge:
> Your requested instance type (a1.xlarge) is not supported in your requested Availability Zone (us-east-2c). Please retry your request by not specifying an Availability Zone or choosing us-east-2a, us-east-2b
Fixup of #202 (a1.xlarge not available in us-east2a), #200 (AMI not autorizing ARM architecture)

chore: use instance type available in all AZ

---

eks-public-cluster.tf
iam-role-nlb.tf

Follow-up of https://github.com/jenkins-infra/aws/pull/200 as currently only the creator of the cluster can be authenticated.

fix(eks-public): manage aws-auth configmap and add users

---

locals.tf
vpc.tf

fix: unique random suffix for eks-public cluster name

---

eks-public-cluster.tf

Fix vpc-cni addon installation, tested locally.
Follow-up of https://github.com/jenkins-infra/aws/pull/218

fix(eks-public): use both private and public subnets

---

eks-cluster.tf
vpc.tf

Make some space to allow deploying vpc-cni addon without issue as it needs a block of /28 available IPs (16)
Cf https://aws.amazon.com/premiumsupport/knowledge-center/eks-cni-plugin-troubleshooting/
Ref: https://github.com/jenkins-infra/helpdesk/issues/2752

fix: add more private subnets and use the first 3 of them for eks-cluster

---

eks-public-cluster.tf
iam-role-nlb.tf
providers.tf

Reverts jenkins-infra/aws#224 and specify a range of private_subnets [not used by eks-cluster](https://github.com/jenkins-infra/aws/blob/main/eks-cluster.tf#L14-L16).

Revert "chore: temporary remove eks-public cluster" and set own private_subnets for eks-public

---

eks-role-autoscaler.tf

Ref: https://github.com/jenkins-infra/helpdesk/issues/2752
<details>
<summary>Current autoscaler pod error log:</summary>
```
encoding/json.(*Decoder).refill(0x4000b2c280)
/usr/local/go/src/encoding/json/stream.go:165 +0x18c
encoding/json.(*Decoder).readValue(0x4000b2c280)
/usr/local/go/src/encoding/json/stream.go:140 +0xac
encoding/json.(*Decoder).Decode(0x4000b2c280, {0x3066f20, 0x4000b78540})
/usr/local/go/src/encoding/json/stream.go:63 +0x68
k8s.io/apimachinery/pkg/util/framer.(*jsonFrameReader).Read(0x4000b6b320, {0x4000b41400, 0x400, 0x400})
/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/framer/framer.go:152 +0x1e8
k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode(0x40008679f0, 0x0, {0x3d8f808, 0x4000b7a680}) …
```

fix: allow assume autoscaler role via irsa for eks-public

---

eks-public-cluster.tf

Fix following error when deploying an exposed service in eks-public:
> Error: release artifact-caching-proxy failed, and has been uninstalled due to atomic being set: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://public-nginx-ingress-ingress-nginx-controller-admission.public-nginx-ingress.svc:443/networking/v1/ingresses?timeout=10s": context deadline exceeded
Ref: https://github.com/kubernetes/ingress-nginx/issues/5401#issuecomment-1205318311

fix(eks-public): add ingress so the cluster can communicate with the ingress controller

---

Jenkinsfile_k8s
eks-cluster.tf

When there is no activity on ci.jenkins.io, no need to keep a machine up ($$$).
Digital Ocean cluster is available so always there to cold-jumpstart agents.

Fix(eks) ensure scale down to zero is enabled for the big node pool 

---

eks-public-cluster.tf

should rebuild the terraform eks-public with amd64 instead of ARM

fix(eks-public): changing to amd64

---

eks-public-cluster.tf

From https://dev.to/aws-builders/install-manage-amazon-eks-add-ons-with-terraform-2dea with really interesting information like this one, to be analysed and reviewed:
> Amazon EKS automatically installs self-managed add-ons such as the Amazon VPC CNI, kube-proxy, and CoreDNS for every cluster, but you can change the default configuration of the add-ons and update them when desired.

hotfix(eks-public): correct EBS CSI addon name

---

vpc.tf

- Using `tags` has impact on other network resources than subnets: when tags are removed from the EIP, it messes up with the nat gateway association
- Spread the outbound traffic per availability zone ("AZ"): https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest#one-nat-gateway-per-availability-zone
- Remove unused public subnets

cleanup(vpcs) remove unused public subnets + remove unused tags + spread nat gateways

---

eks-public-cluster.tf

HTTP egresds is required for cert-manager http01 validation (at least?).

fix(eks-public) allow outgoing HTTP traffic

---

eks-cluster.tf
eks-public-cluster.tf

FIx the error
```
Plan: 2 to add, 0 to change, 0 to destroy.
module.eks_irsa_ebs.aws_iam_role.this[0]: Creating...
╷
│ Error: failed creating IAM Role (ebs-csi-controller-sa): EntityAlreadyExists: Role with name ebs-csi-controller-sa already exists.
│ 	status code: 409, request id: c00f4c83-9479-42c4-a112-659799b9b4b3
│ 
│   with module.eks_irsa_ebs.aws_iam_role.this[0],
│   on .terraform/modules/eks_irsa_ebs/modules/iam-assumable-role-with-oidc/main.tf line 86, in resource "aws_iam_role" "this":
│   86: resource "aws_iam_role" "this" {
│ 
```

fix(eks*) add cluster short name as suffix for each IRSA

---

eks-cluster.tf
eks-public-cluster.tf
iam-roles-eks.tf

That one was pretty painful. No thanks to the awfull EKS documentation :'( 
- Subtly hidden in https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html (tab "AWS CLI", section "2."), it appears that the IAM Role needs to be configured with a "OIDC trusted audience". Haven't tried without this, but better sticking to the documentation. As per https://registry.terraform.io/modules/terraform-aws-modules/iam/aws/latest/submodules/iam-assumable-role-with-oidc#inputs we can use `oidc_fully_qualified_audiences` for this.
- Absent from EKS documentation: there was some IAM permissions missing to Create/Delete EC2 volumes (yes....). Found the correct permissions in the AWS EBS CSI helm chart: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md#set-up-driver-p …

fix(eks*) define versions, IRSA(when required) and configuration policies for addons

---

eks-public-cluster.tf

With only 1 Elastic IP and 1 subnet, the loadbalancer cannot contact the EKS nodes/pods which are in a different AZs then the LB's.
There are 2 solutions:
- Enable cross-zone balancing (as per https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#cross-zone-load-balancing)
- ✅ Only 1 static IP, easier for DNS management
- 🔴 Less availability: if the AZ where the LB is created is failing, then no more LB
- Define multiple AZ with 1 elastic IP for each
- ✅ High availability for the LB when an AZ goes down
- ✅ Default supported setup by the [AWS Load Balancer Controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/annotations/#eip-allocations)
- 🔴 we pay for each Elastic IP …

fix(eks-public) correct LB setup by using 1 EIP per AZ

---

eks-cluster.tf
eks-public-cluster.tf
locals.tf

Related to #304 : the upgrade guide of the EKS module (18.x -> 19.x) mentions the need to remove the default security group created for each node group.
This security group is empty for us so that should be ok:
More details: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-19.0.md#eks-managed-node-groups

cleanup(eks*) delete default (empty) node security groups

---

eks-cluster.tf
eks-public-cluster.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/3305.
This PR adds back the tagging feature for the EKS clusters (defined using the eks terraform module).
By using static values not using Terraform `locals` values, the dependency tree is now complete and does not throw any `depends_on` error.
It allows disabling the cluster security group tagging, ensuring that the AWS LB controller is not confused by finding 2 sec. groups with the expected tag (ref. https://github.com/jenkins-infra/helpdesk/issues/3305#issuecomment-1410408113).

fix(cik8s,eks-public) add back global tags and disable cluster SG tagging

---

eks-public-cluster.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/3305
This PR introduces the following changes (already applied manually to validate):
- Remove all node pools except the one in the `us-east-2a` availability zone where the ACP PVC are created. This node pool is defined with the former autoscaling attributes min/max/desired.
- Add 2 new storage classes defining a topology in `us-east-2a` to avoid the node pool spawning nodes in another AZ than the PVCs
Please note that I was not able to find a way to extract the availability zone value dynamically but did not try a lot.

fix(eks-public) only use a single node pool pinned to a single AZ and define custom storage classes

---

eks-public-cluster.tf

as per https://github.com/jenkins-infra/helpdesk/issues/3425#issuecomment-1456373704 aws needed this flag to allow volume expansion.

fix(eks-public): change storage classes definitions to allow volume expansion

---

eks-cluster.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/3423, this PR increases the size of the cik8s's agents node pool from 20G (default) to 200 (same as current size in DigitalOcean cluster).
Documentation about this change in the Terraform's EKS module we use:
- https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1739
- https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1830

set cik8s agent node pools disk size to 200G

---

locals.tf

Set "release" AWS security group to the same IP as "infraci" since release.ci.jenkins.io has been moved from the `prodpublick8s` cluster (`52.177.88.13` public IP defined in the `MC_prodpublick8s_prodpublick8s_eastus2` resource group) to the `privatek8s` one. (`20.96.66.246` public IP defined in the `MC_prod-privatek8s_privatek8s-emerging-ram_eastus2` resource group)
Similar to https://github.com/jenkins-infra/aws/pull/322
Ref: https://github.com/jenkins-infra/helpdesk/issues/2844

feat(release.ci): update public IP to allow incoming SSH connections to agents

---

locals.tf

Follow-up of https://github.com/jenkins-infra/aws/pull/373#issuecomment-1488637908 & https://github.com/jenkins-infra/kubernetes-management/pull/3774
As none of the current release jobs uses VM agent and as we're not building Docker image on release.ci.jenkins.io (yet), this PR removes the corresponding AWS security group values.

cleanup: remove release.ci unused AWS security group

---

eks-cluster.tf

This PR originates from https://github.com/jenkins-infra/helpdesk/issues/3502 trying to control cloud costs.
The jenkinsci/bom builds on ci.jenkins.io are complex builds which generates a lot of parallel steps (~300) which is quite costy. Their rate is increasing and it also competes for agent resources with plugins (or other builds).
This PR is a first step forward which introduces 1 new node pool dedicated for bom build and 1 optimization to the current AWS node pool. I should have done in 2 PRs, but the Node pools manipulation on EKS are abusively long (~30 min) so I prefer changing them in one shot.
- Optimization to the current nodepool switches to the "compute optimized" instances line to decrease the costs and the probablity of spot eviction
- Ref. …

feat(eks) split and optimize node pools for ci.jenkins.io usage (bom vs. plugins)

---

eks-public-cluster.tf

Switching our users from IAM to SSO requires an ARN configmap change

fix(eks-public) use the new infra-admin SSO ARN

---

ci.jenkins.io.tf

As per [jenkins-infra/helpdesk#3496](https://github.com/jenkins-infra/helpdesk/issues/3496#issuecomment-1517950802), this PR creates the necessary S3 buckets and policies for handling an S3 Artifact Manager for ci.jenkins.io.
Tested with a local controller instance with success.
Please note that the IAM policy described in https://plugins.jenkins.io/artifact-manager-s3/ is incomplete and a documentation PR will be sent (it's missing the `"s3:GetBucketLocation"` permission).
Also, as per https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/, the default setup for S3 bucket changes, hence the additional bucket policy in this PR (otherwise configuration of the bucket is valid in the Jenkins AWS administration panel, but the jobs are failing to …

feat(ci.jenkins.io) add an S3 bucket, associated IAM user and policies for artifact management

---

eks-cluster.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/3521
This PR adds a new node pool on the EKS cluster `cik8s`.
The goal is, folllowing experiementations in https://github.com/jenkinsci/bom/pull/1969, to reduce the initial scope and deliver the "resource split" between bom and plugins.
Since increasing the size of VM (to execute more pods at the same time) led to contentions not diasgnosed yet, the choice is to keep the same sizing as we have today.
This node pool is reserved for the `bom` builds on ci.jenkins.io through the use of taints.
The size of the nodes in this new pool is the same as the current node pool used for both plugins and `bom` builds.
[boyscout improvements]
- The node label `"ci.jenkins.io/agents-density"` was missing on the current node pool: it's added …

feat(cik8s) add a new 3x node pool dedicated to the bom builds

---

eks-cluster.tf
eks-public-cluster.tf

While working on https://github.com/jenkins-infra/helpdesk/issues/3521, I wasn't able to access the cik8s cluster to check its namespaces: neither locally or on my AWS Console.
This PR fixes the issue for the whole SRE team: same thing as https://github.com/jenkins-infra/aws/pull/393 but for the `cik8s` cluster

fix(cik8s) manage aws_auth configmap to add the new AWS SSO infra-admin group

---

eks-public-cluster.tf
locals.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/3542, this PR uses a new user to administrate charts from jenkins-infra/kubernetes-management, which name follows the naming convention (and it rotates the existing credentials).

feat(eks public) change "charter" IAM user

---

cik8s-cluster.tf
eks-public-cluster.tf

Deployment of https://github.com/jenkins-infra/aws/pull/398 failed with the dreaded `dial tcp [::1]:80: connect: connection refused` after cluster creation.
This PR applies the trick from https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2501#issuecomment-1468836777 to fix this issue

fix(cik8s) add missing kubernetes provider

---

updatecli/updatecli.d/terraform-modules/eks.yml
updatecli/updatecli.d/terraform-modules/irsa.yaml

Closes #392  (superseds) as the manifest fingerprints will change.

chore(updatecli) fix manifest after renaming eks-cluster to cik8s-cluster

---

cik8s-cluster.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/3542
This PR adds the 3 node pools to handle workload from ci.jenkins.io in the `cik8s` cluster.

feat(cik8s) add 3 node pools for agents

---

cik8s-cluster.tf

We started with the minimalistic set of IAM permissions from https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html
But given the set of errors we have in the autoscaler logs:
```
I0429 12:17:14.342961       1 aws_manager.go:185] Found multiple availability zones for ASG "eks-spot-linux-24xlarge-20230426083600396100000013-20c3de5a-43bf-d7b2-52a9-334975546a73"; using us-east-2a for failure-domain.beta.kubernetes.io/zone label
E0429 12:17:14.463603       1 managed_nodegroup_cache.go:133] Failed to query the managed nodegroup spot-linux-24xlarge-20230426083600396100000013 for the cluster cik8s-ENRZrfwf while looking for labels/taints: AccessDeniedException: User: arn:aws:sts::200564066411:assumed-role/cluster-autoscaler-aws-cluster-autoscaler-chart-cik8s/1682770623236629083 is not …
```

fix(cik8s) update permissions of the IAM role for autoscaler

---

cik8s-cluster.tf
eks-public-cluster.tf

https://github.com/jenkins-infra/helpdesk/issues/3582
This PR treats both clusters at the same time

feat(cik8s, eks-public) bump EKS and addons to latest 1.25.x available versions

---

cik8s-cluster.tf
eks-public-cluster.tf
providers.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/3679
Same as https://github.com/jenkins-infra/digitalocean/pull/134 + https://github.com/jenkins-infra/digitalocean/pull/136 but for AWS
Note: There is an AWS IAM "eks_charter" user added to the [EKS Auth configmap](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html) : gotta check if we cannot clean it up if the switch to `infraciadmin` SA works without requiring AWS IAM auth.

refactor(cik8s,eks-public) define infraciadmin SA with a terraform module

---

eks-public-cluster.tf

As per https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eip#vpc, the attribute `vpc` is deprecated for resources of type `aws_eip`.
This PR fixes the warning message: no change expected.

chore(eks-public) update deprecated EIP terraform configuration

---

providers.tf

CloudBees owns (and pays for) the AWS account where the Jenkins project hosts the following services:
- Update center (updates.jenkins.io)
- Census (census.jenkins.io)
- Usage (usage.jenkins.io)
- Two EKS clusters used to run workloads for ci.jenkins.io
This PR adds labels to our terraform-managed resources in order to comply with their internal rules.

chore: add CloudBees tags to conform with their AWS account

---

iam-nlb-policy.json

ref. https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.7.0
> We've updated the reference IAM policies to explicitly add the `elasticloadbalancing:DescribeTrustStores` permission for describing the trust stores resources to use the new mTLS feature for ingresses on controller. load balancer and listener resources. We recommend updating your controller IAM policies with the new permissions for your existing installations as well.

feat(IAM) add new permissions on NLB for 2.7.0 release

---

census.jenkins.io.tf
main.tf
network.tf
pkg.origin.jenkins.io.tf
providers.tf
usage.jenkins.io.tf
variables.tf

This PR ensures that only administrator IPs can access the 3 VMs (not Terrafor managed).
It also allows the outbound IPs from the infrastructure interacting (in SSH/Rsync) with these machines:
- trusted.ci.jenkins.io network (permanent agent for update_center2 updates but also ephemeral agents for crawler)
- privatek8s.jenkins.io network (release.ci need to access the VM when packaging the Core releases and infra.ci.jenkins.io need to administrate the VMs with terraform-
This PR also create a SG to allow inbound connections (HTTP and HTTPS) from the internet: the goal is to remove the current SG manually managed in favor of this new one.
cc @MarkEWaite @lemeurherve @smerle33 @timja @daniel-beck @wadeck if you need to add your own public Ip to reach the pkg VM (with the current update …

feat: restrict SSH access to VMs

---

network.tf

The 3 VMs all have their Puppet agent failing because the egress to Puppetmaster on 8140 is blocked.
This PR solves it

fix: allow egress to Puppetmaster for all VMs
