jenkins-infra/aws

- eks-cluster.tf
- vpc.tf
- Fix naming of resources
- Update Cluster to 1.19
> Feat/kube 1.19 update

- Jenkinsfile_k8s
> Fix: notify user on PR... only when on PR builds

- Jenkinsfile_k8s
- eks-cluster.tf
> EKS: Add a new admin user to administrate charts

- Makefile
- eks-cluster.tf
> Encrypt EKS secrets with a new KMS key

- Makefile
- ec2-agents.tf
- eks-cluster.tf
- irsa.tf
- locals.tf
- vpc.tf
> feat: prepare autoscaling for the EKS cluster through IRSA

- eks-cluster.tf
> feat(eks) add a worker pool for utils services and a spot worker pool (INFRA-3104)

- updatecli/updatecli.d/ciPodTemplate.yml
> chore(updatecli) fix updatecli manifest for version 0.15.0+

- eks-cluster.tf
> Revert "feat: integrate VPC CNI, kube-proxy and CoreDNS EKS addons"

- updatecli/updatecli.d/terraform-modules/eks.yml
- updatecli/updatecli.d/terraform-modules/irsa.yaml
- updatecli/updatecli.d/terraform-modules/vpc.yaml
- updatecli/updatecli.d/terraform-providers.yaml
> chore(updatecli) moaaaaar typos

- ec2-agents.tf
while working on https://github.com/jenkins-infra/packer-images/pull/164
> adding oubound rules for winRM http and httpS

- eks-role-autoscaler.tf
in order to avoid error 403 with autoscaler
> fix: add the ec2:DescribeInstanceTypes role

- ec2-agents.tf
- locals.tf
trying to convert to dynamical generation some parts of the manifest.
the aim is to have a more easily readable data as source for updatecli from other repositories 
https://github.com/jenkins-infra/kubernetes-management/pull/1983
Work In Progress
> dynamically generate the aws_security_group from local map variable

- .terraform.lock.hcl
- Jenkinsfile_k8s
- updatecli/scripts/terraform-get-upgraded-lockfile.sh
- versions.tf
as per https://github.com/jenkins-infra/shared-tools/issues/8 bump terraform version 1.1.x
> enhancement: bump terraform to 1.1.7

- CODEOWNERS
Part of https://github.com/jenkins-infra/helpdesk/issues/2829
> chore: add CODEOWNERS with "terraform" and "kubernetes" teams

- Jenkinsfile_k8s
- updatecli/updatecli.d/hashicorp-tools.yml
> Chore: bump hashicorp tools to 0.4.4 + fix updatecli tracking for hashicorp-tools

- variables.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/2866
> feat(eks) bump Kubernetes version to 1.21 baseline

- variables.tf
as per https://github.com/jenkins-infra/helpdesk/issues/2930
> feat(AWS/EKS): upgrade kubernetes version to 1.22

- .terraform.lock.hcl
- Jenkinsfile_k8s
- eks-cluster.tf
- eks-role-autoscaler.tf
Close #190
Close #189
Close #188
Close #187
> chore(regroup-pr): update dependencies

- eks-public-cluster.tf
> fixup: allow using ARM instance type on `eks-public`

- updatecli/updatecli.d/hashicorp-tools.yml
- updatecli/updatecli.d/terraform-modules/eks.yml
- updatecli/updatecli.d/terraform-modules/irsa.yaml
- updatecli/updatecli.d/terraform-modules/vpc.yaml
- updatecli/updatecli.d/terraform-providers.yaml
- versions.tf
> Chore(updatecli,shared-tools, providers) cleanup for tracking all providers

- providers.tf
- versions.tf
Closes #221 (and closes #220 as duplicate)
> fix(providers) add definition of the 'random' provider

- eks-role-autoscaler.tf
- locals.tf
Fixup of https://github.com/jenkins-infra/aws/pull/232
> fixup: unique autoscaler role names

- updatecli/updatecli.d/hashicorp-tools.yml
- updatecli/updatecli.d/terraform-modules/eks.yml
- updatecli/updatecli.d/terraform-modules/irsa.yaml
- updatecli/updatecli.d/terraform-modules/vpc.yaml
- updatecli/updatecli.d/terraform-providers.yaml
- Closes #235 #230 #231 #229 
- Fixes the "v" prefix behaviorial change introduced by updatecli 0.35.1 
- Cleans up some manifest syntax
> chore(updatecli) fix manifests for 0.35.1 + eks-public

- ec2-agents.tf
- eks-cluster.tf
- eks-public-cluster.tf
- eks-role-autoscaler.tf
- iam-role-nlb.tf
- iam-role-updatecli.tf
- providers.tf
Ref: https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider
> feat: use default_tags

- eks-public-cluster.tf
- eks-role-autoscaler.tf
- iam-role-ebs-csi.tf
- locals.tf
Will be needed soon or later (cf note on https://docs.aws.amazon.com/eks/latest/userguide/storage-classes.html) Also, might help me with my permission problems with the artifact-caching-proxy, different from the ones I encountered on the other clusters
> feat(eks-public): add EBS CSI addon

- updatecli/updatecli.d/terraform-modules/irsa.yaml
Excerpt from https://github.com/jenkins-infra/aws/pull/255
> fix(updatecli): correct targets.files for irsa manifest

- locals.tf
- vpc.tf
- Fix namespace
- Add back tags only on public subnets without changing names
> fix(eks-public) correct configuration to allow NLB controller working as expected

- eks-public-cluster.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3053
upgrade kubernetes to 1.23
> feat(kub/public): upgrade to 1.23

- eks-cluster.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3053
upgrade the EKS cluster to 1.23
> feat(EKS): upgrade to kubernetes 1.23

- eks-cluster.tf
- locals.tf
Ref: https://github.com/jenkins-infra/helpdesk/issues/3053
> fix(ebs-csi): correct namespace for irsa on eks-public + add irsa on eks-cluster

- locals.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/2844
> feat(infra.ci) update public IP to allow incoming SSH connections to agents

- eks-public-cluster.tf
This PR tries to implement https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2186 to work around https://github.com/jenkins-infra/helpdesk/issues/3305#issuecomment-1421081843.
PS: I've backed-up the configmaps on my machine since the diff shows it will be edited.
> feat(eks-public) add 1 node pool per AZ

- eks-cluster.tf
Ref: https://github.com/jenkins-infra/helpdesk/issues/3387
> chore: update `cik8s` cluster to Kubernetes 1.24

- eks-public-cluster.tf
Ref: https://github.com/jenkins-infra/helpdesk/issues/3387
> chore: update eks-public cluster to Kubernetes 1.24

- eks-cluster.tf
Replace #359 
Ref: https://github.com/jenkins-infra/helpdesk/issues/3423
> feat(eks-cluster): set `block_device_mappings` to increase node disk size

- eks-public-cluster.tf
- iam-role-updatecli.tf
Fix the error `Error: getting user: NoSuchEntity: The user with name updatecli cannot be found.`
> fix(iam) manage technical user updatecli

- .terraform.lock.hcl
- ci.jenkins.io.tf
- cik8s-cluster.tf
- ec2-agents.tf
- eks-public-cluster.tf
- iam-role-updatecli.tf
- iam-roles-eks.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3753
> chore: migrate from tfsec to trivy

- cik8s-cluster.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3683#issuecomment-1794913444
> feat(cik8s) upgrade kubernetes to 1.26 (and addons)

- eks-public-cluster.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3683#issuecomment-1794913444
> feat(eks-public) upgrade kubernetes to 1.26 (and addons)

- Jenkinsfile_k8s
- ci.jenkins.io.tf
- versions.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3823
> chore: use terraform `1.6` instead of `1.1`

- cik8s-cluster.tf
- eks-public-cluster.tf
- locals.tf
- providers.tf
Follow up of #499, certain resources are not tagged due to weirdness of modules and of our setup.
> chore: add subsequent tags for CloudBees policies

- cik8s-cluster.tf
- eks-public-cluster.tf
Note: as we applied these upgrades manually, we expect the diff to show no changes
> feat(eks-public,cik8s) bump addons to latest versions

- cik8s-cluster.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1976757473
> bump(cik8s): kubernetes to 1.27 and addons

- eks-public-cluster.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1976757473
> bump(ekspublic): upgrade to kubernetes 1.27 and addons

- census.jenkins.io.tf
- pkg.origin.jenkins.io.tf
- usage.jenkins.io.tf
fixup of #556 where I forgot to associate the HTTP NSG to the 3 VMs
> fix(census,pkg,usage) add HTTP NSG

- network.tf
- pkg.origin.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4198#issuecomment-2252035383
Fixup of #559
Fixup of #556
> feat(network) allow outbound HTTP for all and SSH/Rsync for pkg

- network.tf
This PR is a fixup of #560 #559 and #556 for https://github.com/jenkins-infra/helpdesk/issues/4196.
It fixes the build errors of https://github.com/jenkins-infra/docker-packaging/pull/133 where an SSH connection attempt is made from an infra.ci.jenkins.io agent but fail due to restrictions by adding the outbound IPs of infra.ci agents (VMs and Kubernetes agents) to the allowed inbound SSH NSG rule.
It also filters out the eventual IPv6 (if any) (cherry picking the technique from #560)
> fix(NSGs) allow inbound SSH from infra.ci agents for management

- network.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2838032516
> feat(network) update SSH source IPs allowed to the VMs

- network.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2839488075
> cleanup: migrate settings from privatek8s to privatek8s-sponsorship cluster

- network.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4653
> feat(network) allow outbound rsync to internet
